feat: enable docker build stage in pipeline

diff --git a/monitor/service-monitor b/monitor/service-monitor
--- a/monitor/service-monitor
+++ b/monitor/service-monitor
@@ -1,26 +1,24 @@
 #!/bin/bash
 
-BASE_DIR="$(cd "$(dirname "$0")/.." && pwd)"
+SERVICES=("NetworkManager" "sshd" "cronie")
 
-source "$BASE_DIR/utils/log-helper"
+for service in "${SERVICES[@]}"
+do
+    if command -v systemctl >/dev/null 2>&1; then
 
-SERVICE_NAME=$1
+        if systemctl is-active --quiet "$service"
+        then
+            echo "$service Healthy"
 
-STATUS=$(systemctl is-active "$SERVICE_NAME")
+        else
+            echo "$service DOWN"
 
-if [ "$STATUS" != "active" ]
-then
-    echo "$SERVICE_NAME is DOWN"
+            systemctl restart "$service" \
+            || echo "Unable to restart $service"
+        fi
 
-    write_log "SERVICE ALERT - $SERVICE_NAME DOWN"
+    else
+        echo "Skipping $service (container mode)"
+    fi
 
-    sudo systemctl restart "$SERVICE_NAME"
-
-    write_log "AUTO-HEALING - Restarted $SERVICE_NAME"
-
-    echo "$SERVICE_NAME restarted"
-else
-    echo "$SERVICE_NAME is RUNNING"
-
-    write_log "SERVICE HEALTHY - $SERVICE_NAME RUNNING"
-fi
+done
